### ISSUE TITLE
Lisnownet

### ISSUE THREAD

**Issue by lyandstella** [umautobots/lisnownet#7]
您好，我想跑通Lisnownet代码，可是我出现了代码报错解决不了，您方便个给我点建议吗？谢谢
Traceback (most recent call last):
  File "/workspace/./train.py", line 193, in <module>
    l_dwt, l_fft = losses.sparsity_loss(y)
  File "/workspace/tools/losses.py", line 16, in sparsity_loss
    return dwt_loss(x), fft_loss(x)
  File "/workspace/tools/losses.py", line 39, in fft_loss
    y = utils.fft2(x)
  File "/workspace/tools/utils.py", line 44, in fft2
    y = fft.rfft2(x, norm='ortho')
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

**Comment by tn00364361** [comment]
Did you use the Dockerfile to setup the environment? Also, can you post the details of your system? For example, the operating system and the GPU model.

**Comment by lyandstella** [comment]
> Did you use the Dockerfile to setup the environment? Also, can you post the details of your system? For example, the operating system and the GPU model.

您好，我使用了Dockerfile，环境按照Lisnownet的readme设置的。操作系统是ubuntu 20.04；Gpu是NVIDIA GeForce RTX 4060 Ti 16GB，显卡驱动是560.35.03。
我当时在构建docker镜时候，没成功。我就改了dockerfile里面内容，带#是原文件的。
# install python modules in /root/.local
# 原来 RUN pip3 install --user --no-cache-dir -r /tmp/requirements.txt
修改RUN pip3 install --no-cache-dir -r /tmp/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
修改RUN pip3 install --no-cache-dir --default-timeout=100 -r /tmp/requirements.txt

**Comment by lyandstella** [comment]
> Did you use the Dockerfile to setup the environment? Also, can you post the details of your system? For example, the operating system and the GPU model.

您好，我使用了Dockerfile，环境按照Lisnownet的readme设置的。操作系统是ubuntu 20.04；Gpu是NVIDIA GeForce RTX 4060 Ti 16GB，显卡驱动是560.35.03。
我当时在构建docker镜像时候，没成功。我就改了dockerfile里面内容。（下面是我的修改）
#install python modules in /root/.local
#原来 RUN pip3 install --user --no-cache-dir -r /tmp/requirements.txt
修改RUN pip3 install --no-cache-dir -r /tmp/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
修改RUN pip3 install --no-cache-dir --default-timeout=100 -r /tmp/requirements.txt

**Comment by lyandstella** [comment]
> Did you use the Dockerfile to setup the environment? Also, can you post the details of your system? For example, the operating system and the GPU model.
您好，我使用了Dockerfile，环境按照Lisnownet的readme设置的。操作系统是ubuntu 20.04；Gpu是NVIDIA GeForce RTX 4060 Ti 16GB，显卡驱动是560.35.03。
我当时在构建docker镜像时候，没成功。我就改了dockerfile里面内容。我就是用最后两行代码替换了原dockerfile里面那行代码。
#install python modules in /root/.local
# RUN pip3 install --user --no-cache-dir -r /tmp/requirements.txt（原文件内容）
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install --no-cache-dir --default-timeout=100 -r /tmp/requirements.txt

**Comment by lyandstella** [comment]
> Did you use the Dockerfile to setup the environment? Also, can you post the details of your system? For example, the operating system and the GPU model.

    您好，我使用了Dockerfile，环境按照Lisnownet的readme设置的。操作系统是ubuntu 20.04；Gpu是NVIDIA GeForce RTX 4060 Ti 16GB，显卡驱动是560.35.03。
    我当时在构建docker镜像时候，没成功。我就改了dockerfile里面内容。我就是用最后两行代码替换了原dockerfile里面那行代码。
# install python modules in /root/.local
# RUN pip3 install --user --no-cache-dir -r /tmp/requirements.txt（原文件内容）
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install --no-cache-dir --default-timeout=100 -r /tmp/requirements.txt

**Comment by lyandstella** [comment]
> Did you use the Dockerfile to setup the environment? Also, can you post the details of your system? For example, the operating system and the GPU model.

您好，我使用了Dockerfile，环境按照Lisnownet的readme设置的。操作系统是ubuntu 20.04；Gpu是NVIDIA GeForce RTX 4060 Ti 16GB，显卡驱动是560.35.03。 我当时在构建docker镜像时候，没成功。我就改了dockerfile里面内容。我就是用最后两行代码替换了原dockerfile里面那行代码。
#install python modules in /root/.local
#RUN pip3 install --user --no-cache-dir -r /tmp/requirements.txt（原文件内容）
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install --no-cache-dir --default-timeout=100 -r /tmp/requirements.txt

**Comment by tn00364361** [comment]
Okay, there was [a bug in CUDA 11.7](https://github.com/pytorch/pytorch/issues/88038) and was resolved in CUDA 11.8. I updated `requirements.txt` to use newer package versions. Can you try it out?

**Comment by lyandstella** [comment]
> Okay, there was [a bug in CUDA 11.7](https://github.com/pytorch/pytorch/issues/88038) and was resolved in CUDA 11.8. I updated `requirements.txt` to use newer package versions. Can you try it out?

谢谢您啦。我这个问题已经解决了，我直接在anaconda创建的环境，cuda 是12.4，torch都是根据这个版本cuda装的，也可以跑通。我会再次尝试用您更新的requirements，在docker里面拉一下镜像环境，💪💪💪
